context:
  build_number: 0

package:
  name: r-microbenchmark
  version: 1.5.0

source:
  url:
    - https://cran.r-project.org/src/contrib/microbenchmark_1.5.0.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/microbenchmark/microbenchmark_1.5.0.tar.gz
  sha256: 3d1e92a9206811ad128b28795d20a0d31da5f0c29ea7f1caaf1194ed3e49765f

build:
  number: ${{ build_number }}
  script:
    - if: win
      then: R CMD INSTALL --build . %R_ARGS%
      else: R CMD INSTALL --build . ${R_ARGS}

requirements:
  build:
    - if: win
      then:
        - gcc_win-64
        - m2-base
        - m2-make
        - m2-autoconf
      else:
        - ${{ compiler('c') }}
        - make
        - autoconf

  host:
    - r-base 4.5.*

  run:
    - r-base 4.5.*

tests:
  - script:
      - Rscript -e 'library("microbenchmark")'

about:
  homepage: https://github.com/joshuaulrich/microbenchmark/
  repository: https://github.com/joshuaulrich/microbenchmark/
  license: BSD-2-Clause
  summary: Accurate Timing Functions