context:
  build_number: 0

package:
  name: r-grpreg
  version: 3.6.0

source:
  - url:
      - https://cran.r-project.org/src/contrib/grpreg_3.6.0.tar.gz
      - https://cran.r-project.org/src/contrib/Archive/grpreg/grpreg_3.6.0.tar.gz
    sha256: 1270e87b7d44913de44295b35ba58a19d946ecd54b072232d6b2b5ff85e2ed8d

build:
  number: ${{ build_number }}
  script:
    - if: win
      then: R CMD INSTALL --build . %R_ARGS%
      else: R CMD INSTALL --build . ${R_ARGS}

requirements:
  build:
    - if: win
      then:
        - gcc_win-64
        - gxx_win-64
        - m2-base
        - m2-make
      else:
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - make

  host:
    - r-base 4.5.*
    - r-matrix

  run:
    - r-base 4.5.*
    - r-matrix

tests:
  - script:
      - Rscript -e 'library("grpreg")'

about:
  homepage: https://pbreheny.github.io/grpreg/
  summary: Regularization Paths for Regression Models with Grouped Covariates
  description: |-
    Efficient algorithms for fitting the regularization path of linear
    regression, GLM, and Cox regression models with grouped penalties.
  license: GPL-3.0-only
  repository: https://github.com/cran/grpreg